//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linear_Programming_381.Forms
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null!;

        private Label lblTitle;
        private Label lblInput;
        private TextBox txtInputPath;
        private Button btnBrowse;
        private Button btnLoad;
        private Button btnSolve;
        private Button btnExport;
        private Button btnClear;

        private Label lblModel;
        private Label lblOutput;

        private TextBox txtModel;
        private RichTextBox txtOutput;

        private Label lblStatus;

        protected override void Dispose(
            bool disposing)
        {
            if (disposing &&
                components != null)
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            lblTitle = new Label();
            lblInput = new Label();
            txtInputPath = new TextBox();
            btnBrowse = new Button();
            btnLoad = new Button();
            btnSolve = new Button();
            btnExport = new Button();
            btnClear = new Button();

            lblModel = new Label();
            lblOutput = new Label();

            txtModel = new TextBox();
            txtOutput = new RichTextBox();

            lblStatus = new Label();

            SuspendLayout();

            // MainForm
            AutoScaleDimensions =
                new SizeF(8F, 20F);

            AutoScaleMode =
                AutoScaleMode.Font;

            ClientSize =
                new Size(1200, 750);

            MinimumSize =
                new Size(1000, 650);

            StartPosition =
                FormStartPosition.CenterScreen;

            Text =
                "LP381 - Linear Programming Solver";

            // Title
            lblTitle.AutoSize = true;

            lblTitle.Font =
                new Font(
                    "Segoe UI",
                    20F,
                    FontStyle.Bold);

            lblTitle.Location =
                new Point(30, 20);

            lblTitle.Text =
                "LP381 LINEAR PROGRAMMING SOLVER";

            // Input label
            lblInput.AutoSize = true;

            lblInput.Location =
                new Point(32, 80);

            lblInput.Text =
                "Input File:";

            // Input textbox
            txtInputPath.Location =
                new Point(110, 76);

            txtInputPath.Size =
                new Size(650, 27);

            // Browse
            btnBrowse.Location =
                new Point(775, 74);

            btnBrowse.Size =
                new Size(100, 32);

            btnBrowse.Text =
                "Browse";

            btnBrowse.Click +=
                btnBrowse_Click;

            // Load
            btnLoad.Location =
                new Point(890, 74);

            btnLoad.Size =
                new Size(110, 32);

            btnLoad.Text =
                "Load Model";

            btnLoad.Click +=
                btnLoad_Click;

            // Solve
            btnSolve.Location =
                new Point(30, 125);

            btnSolve.Size =
                new Size(180, 45);

            btnSolve.Text =
                "Primal Simplex";

            btnSolve.Font =
                new Font(
                    "Segoe UI",
                    10F,
                    FontStyle.Bold);

            btnSolve.Click +=
                btnSolve_Click;

            // Export
            btnExport.Location =
                new Point(225, 125);

            btnExport.Size =
                new Size(180, 45);

            btnExport.Text =
                "Export Results";

            btnExport.Click +=
                btnExport_Click;

            // Clear
            btnClear.Location =
                new Point(420, 125);

            btnClear.Size =
                new Size(180, 45);

            btnClear.Text =
                "Clear";

            btnClear.Click +=
                btnClear_Click;

            // Model label
            lblModel.AutoSize = true;

            lblModel.Font =
                new Font(
                    "Segoe UI",
                    11F,
                    FontStyle.Bold);

            lblModel.Location =
                new Point(30, 195);

            lblModel.Text =
                "Programming Model";

            // Output label
            lblOutput.AutoSize = true;

            lblOutput.Font =
                new Font(
                    "Segoe UI",
                    11F,
                    FontStyle.Bold);

            lblOutput.Location =
                new Point(470, 195);

            lblOutput.Text =
                "Solver Output";

            // Model textbox
            txtModel.Location =
                new Point(30, 225);

            txtModel.Size =
                new Size(400, 420);

            txtModel.Multiline = true;

            txtModel.ReadOnly = true;

            txtModel.ScrollBars =
                ScrollBars.Vertical;

            txtModel.Font =
                new Font(
                    "Consolas",
                    10F);

            // Output
            txtOutput.Location =
                new Point(470, 225);

            txtOutput.Size =
                new Size(690, 420);

            txtOutput.ReadOnly = true;

            txtOutput.Font =
                new Font(
                    "Consolas",
                    10F);

            txtOutput.BackColor =
                Color.White;

            txtOutput.ScrollBars =
                RichTextBoxScrollBars.Both;

            // Status
            lblStatus.AutoSize = true;

            lblStatus.Location =
                new Point(30, 675);

            lblStatus.Text =
                "Ready.";

            // Add controls
            Controls.Add(lblTitle);
            Controls.Add(lblInput);
            Controls.Add(txtInputPath);

            Controls.Add(btnBrowse);
            Controls.Add(btnLoad);
            Controls.Add(btnSolve);
            Controls.Add(btnExport);
            Controls.Add(btnClear);

            Controls.Add(lblModel);
            Controls.Add(lblOutput);

            Controls.Add(txtModel);
            Controls.Add(txtOutput);

            Controls.Add(lblStatus);

            ResumeLayout(false);
            PerformLayout();
        }
    }
}